---
- name: Set up the Nodesource RPM directory for Node.js > 0.10.
  set_fact:
    nodejs_rhel_rpm_dir: "pub_{{ nodejs_version }}"
  when: nodejs_version != '0.10'

- name: Set up the Nodesource RPM variable for Node.js == 0.10.
  set_fact:
    nodejs_rhel_rpm_dir: "pub"
  when: nodejs_version == '0.10'

- name: Define repo path when custom is not defined
  set_fact:
    nodejs_repo_url: "https://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
  when: nodejs_repo_url is not defined

- name: Add Nodesource repositories for Node.js.
  yum:
    name: "{{ nodejs_repo_url }}"
    state: present

- name: Ensure Node.js and npm are installed.
  yum:
    name: nodejs
    state: present
    enablerepo: 'epel,nodesource'
